### ISSUE TITLE
To TwinStar format

### ISSUE THREAD

**Issue by harumazzz** [Endlin-Boeingstein/EBToolBox#1]
To TwinStar XFL Format seem does not work anymore, can you adapt the new structure of that toolkit?

**Comment by Endlin-Boeingstein** [comment]
你好，我的GitHub出现了一些问题，导致了我的项目源码无法上传，甚至Release我都是手动打包上传的。
关于TSTK的XFL，由于其结构的大变动，我实在没有办法进行适配互转，抱歉。
未来也许我会有机会去做出一些改变。
Hello, there are some problems with my GitHub, which prevents my project source code from being uploaded. Even for Release, I package and upload it manually.
Regarding TSTK's XFL, due to major changes in its structure, I really have no way to adapt and convert it, sorry. Maybe I will have the opportunity to make some changes in the future.
